// This file contains a list of common Spanish adjectives and their English translations.
// Export as a variable for use in adjectives-script.js

const spanishAdjectives = [
    { spanish: "bueno", english: "good" },
    { spanish: "malo", english: "bad" },
    { spanish: "grande", english: "big, large" },
    { spanish: "pequeño", english: "small, little" },
    { spanish: "nuevo", english: "new" },
    { spanish: "viejo", english: "old" },
    { spanish: "primero", english: "first" },
    { spanish: "último", english: "last" },
    { spanish: "largo", english: "long" },
    { spanish: "corto", english: "short" },
    { spanish: "alto", english: "tall, high" },
    { spanish: "bajo", english: "short, low" },
    { spanish: "joven", english: "young" },
    { spanish: "importante", english: "important" },
    { spanish: "diferente", english: "different" },
    { spanish: "mismo", english: "same" },
    { spanish: "bonito", english: "pretty, nice" },
    { spanish: "feo", english: "ugly" },
    { spanish: "fácil", english: "easy" },
    { spanish: "difícil", english: "difficult" },
    { spanish: "rápido", english: "fast" },
    { spanish: "lento", english: "slow" },
    { spanish: "caro", english: "expensive" },
    { spanish: "barato", english: "cheap" },
    { spanish: "feliz", english: "happy" },
    { spanish: "triste", english: "sad" },
    { spanish: "fuerte", english: "strong" },
    { spanish: "débil", english: "weak" },
    { spanish: "caliente", english: "hot" },
    { spanish: "frío", english: "cold" },
    { spanish: "lleno", english: "full" },
    { spanish: "vacío", english: "empty" },
    { spanish: "claro", english: "clear, light" },
    { spanish: "oscuro", english: "dark" },
    { spanish: "rico", english: "rich, tasty" },
    { spanish: "pobre", english: "poor" },
    { spanish: "famoso", english: "famous" },
    { spanish: "popular", english: "popular" },
    { spanish: "amable", english: "kind, friendly" },
    { spanish: "simpático", english: "nice, pleasant" },
    { spanish: "antipático", english: "unpleasant" },
    { spanish: "inteligente", english: "intelligent" },
    { spanish: "tonto", english: "silly, dumb" },
    { spanish: "interesante", english: "interesting" },
    { spanish: "aburrido", english: "boring" },
    { spanish: "limpio", english: "clean" },
    { spanish: "sucio", english: "dirty" },
    { spanish: "fresco", english: "fresh, cool" },
    { spanish: "seco", english: "dry" },
    { spanish: "mojado", english: "wet" },
    { spanish: "duro", english: "hard" },
    { spanish: "blando", english: "soft" },
    { spanish: "peligroso", english: "dangerous" },
    { spanish: "seguro", english: "safe, sure" },
    { spanish: "cansado", english: "tired" },
    { spanish: "despierto", english: "awake" },
    { spanish: "dormido", english: "asleep" },
    { spanish: "abierto", english: "open" },
    { spanish: "cerrado", english: "closed" },
    { spanish: "ocupado", english: "busy, occupied" },
    { spanish: "libre", english: "free" },
    { spanish: "contento", english: "happy, content" },
    { spanish: "enfermo", english: "sick" },
    { spanish: "sano", english: "healthy" },
    { spanish: "rojo", english: "red" },
    { spanish: "azul", english: "blue" },
    { spanish: "verde", english: "green" },
    { spanish: "amarillo", english: "yellow" },
    { spanish: "negro", english: "black" },
    { spanish: "blanco", english: "white" },
    { spanish: "gris", english: "gray" },
    { spanish: "marrón", english: "brown" },
    { spanish: "rosa", english: "pink" },
    { spanish: "naranja", english: "orange" },
    { spanish: "violeta", english: "violet" },
    { spanish: "fácil", english: "easy" },
    { spanish: "difícil", english: "difficult" },
    { spanish: "corto", english: "short" },
    { spanish: "largo", english: "long" },
    { spanish: "ancho", english: "wide" },
    { spanish: "estrecho", english: "narrow" },
    { spanish: "pesado", english: "heavy" },
    { spanish: "ligero", english: "light (weight)" },
    { spanish: "fino", english: "fine, thin" },
    { spanish: "grueso", english: "thick" },
    { spanish: "recto", english: "straight" },
    { spanish: "torcido", english: "crooked, twisted" },
    { spanish: "corto", english: "short" },
    { spanish: "largo", english: "long" },
    { spanish: "cerca", english: "near" },
    { spanish: "lejos", english: "far" },
    { spanish: "profundo", english: "deep" },
    { spanish: "superficial", english: "superficial, shallow" },
    { spanish: "lleno", english: "full" },
    { spanish: "vacío", english: "empty" },
    { spanish: "fuerte", english: "strong" },
    { spanish: "débil", english: "weak" },
    { spanish: "duro", english: "hard" },
    { spanish: "blando", english: "soft" },
    { spanish: "rico", english: "rich, tasty" },
    { spanish: "pobre", english: "poor" },
    { spanish: "feliz", english: "happy" },
    { spanish: "triste", english: "sad" },
    { spanish: "amable", english: "kind, friendly" },
    { spanish: "simpático", english: "nice, pleasant" },
    { spanish: "antipático", english: "unpleasant" },
    { spanish: "inteligente", english: "intelligent" },
    { spanish: "tonto", english: "silly, dumb" },
    { spanish: "interesante", english: "interesting" },
    { spanish: "aburrido", english: "boring" }
];

export { spanishAdjectives };