// This file contains a list of common Spanish adverbs and their English translations.
// Export as a variable for use in adverbs-script.js

const spanishAdverbs = [
    { spanish: "muy", english: "very" },
    { spanish: "más", english: "more" },
    { spanish: "menos", english: "less" },
    { spanish: "bien", english: "well" },
    { spanish: "mal", english: "badly" },
    { spanish: "aquí", english: "here" },
    { spanish: "allí", english: "there" },
    { spanish: "ahora", english: "now" },
    { spanish: "entonces", english: "then" },
    { spanish: "después", english: "after, later" },
    { spanish: "antes", english: "before" },
    { spanish: "siempre", english: "always" },
    { spanish: "nunca", english: "never" },
    { spanish: "también", english: "also, too" },
    { spanish: "tampoco", english: "neither, either" },
    { spanish: "ya", english: "already, now" },
    { spanish: "todavía", english: "still, yet" },
    { spanish: "casi", english: "almost" },
    { spanish: "solo", english: "only" },
    { spanish: "sólo", english: "only, just" },
    { spanish: "quizá", english: "maybe, perhaps" },
    { spanish: "tal vez", english: "maybe, perhaps" },
    { spanish: "si", english: "if" },
    { spanish: "cuando", english: "when" },
    { spanish: "donde", english: "where" },
    { spanish: "cómo", english: "how" },
    { spanish: "por qué", english: "why" },
    { spanish: "a veces", english: "sometimes" },
    { spanish: "nunca", english: "never" },
    { spanish: "pronto", english: "soon" },
    { spanish: "tarde", english: "late" },
    { spanish: "temprano", english: "early" },
    { spanish: "despacio", english: "slowly" },
    { spanish: "rápidamente", english: "quickly" },
    { spanish: "lejos", english: "far" },
    { spanish: "cerca", english: "near" },
    { spanish: "arriba", english: "up" },
    { spanish: "abajo", english: "down" },
    { spanish: "dentro", english: "inside" },
    { spanish: "fuera", english: "outside" },
    { spanish: "juntos", english: "together" },
    { spanish: "solo", english: "alone" },
    { spanish: "siempre", english: "always" },
    { spanish: "nunca", english: "never" },
    { spanish: "a menudo", english: "often" },
    { spanish: "de vez en cuando", english: "from time to time" },
    { spanish: "de nuevo", english: "again" },
    { spanish: "ya", english: "already, now" },
    { spanish: "todavía", english: "still, yet" },
    { spanish: "apenas", english: "hardly, barely" },
    { spanish: "bastante", english: "enough, quite" },
    { spanish: "demasiado", english: "too much" },
    { spanish: "exactamente", english: "exactly" },
    { spanish: "finalmente", english: "finally" },
    { spanish: "inmediatamente", english: "immediately" },
    { spanish: "lentamente", english: "slowly" },
    { spanish: "normalmente", english: "normally" },
    { spanish: "perfectamente", english: "perfectly" },
    { spanish: "posiblemente", english: "possibly" },
    { spanish: "probablemente", english: "probably" },
    { spanish: "recientemente", english: "recently" },
    { spanish: "seguramente", english: "surely" },
    { spanish: "simplemente", english: "simply" },
    { spanish: "tranquilamente", english: "calmly" },
    { spanish: "usualmente", english: "usually" }
];

export { spanishAdverbs };