// This file contains the list of the top 250 most common Spanish nouns and their English translations.
// Export as a variable for use in nouns-script.js

const spanishNouns = [
    { spanish: "el tiempo", english: "time, weather" },
    { spanish: "el año", english: "year" },
    { spanish: "la gente", english: "people" },
    { spanish: "el día", english: "day" },
    { spanish: "el hombre", english: "man" },
    { spanish: "la cosa", english: "thing" },
    { spanish: "la mujer", english: "woman" },
    { spanish: "la vida", english: "life" },
    { spanish: "el niño", english: "child, boy" },
    { spanish: "el mundo", english: "world" },
    { spanish: "la parte", english: "part" },
    { spanish: "el momento", english: "moment" },
    { spanish: "el lugar", english: "place" },
    { spanish: "el trabajo", english: "work, job" },
    { spanish: "el caso", english: "case, occasion" },
    { spanish: "la semana", english: "week" },
    { spanish: "el gobierno", english: "government" },
    { spanish: "el punto", english: "point, dot" },
    { spanish: "la empresa", english: "company, business" },
    { spanish: "el número", english: "number" },
    { spanish: "el grupo", english: "group" },
    { spanish: "el problema", english: "problem" },
    { spanish: "el hecho", english: "fact" },
    { spanish: "el país", english: "country" },
    { spanish: "el padre", english: "father" },
    { spanish: "la madre", english: "mother" },
    { spanish: "el amigo", english: "friend (male)" },
    { spanish: "la amiga", english: "friend (female)" },
    { spanish: "el hermano", english: "brother" },
    { spanish: "la hermana", english: "sister" },
    { spanish: "el hijo", english: "son" },
    { spanish: "la hija", english: "daughter" },
    { spanish: "el señor", english: "Mr., gentleman" },
    { spanish: "la señora", english: "Mrs., lady" },
    { spanish: "el chico", english: "boy" },
    { spanish: "la chica", english: "girl" },
    { spanish: "el estudiante", english: "student (male)" },
    { spanish: "la estudiante", english: "student (female)" },
    { spanish: "el profesor", english: "teacher (male)" },
    { spanish: "la profesora", english: "teacher (female)" },
    { spanish: "el amigo", english: "friend (male)" },
    { spanish: "la familia", english: "family" },
    { spanish: "el cuerpo", english: "body" },
    { spanish: "la cabeza", english: "head" },
    { spanish: "el ojo", english: "eye" },
    { spanish: "la mano", english: "hand" },
    { spanish: "el pie", english: "foot" },
    { spanish: "la boca", english: "mouth" },
    { spanish: "el corazón", english: "heart" },
    { spanish: "el amigo", english: "friend (male)" },
    { spanish: "el coche", english: "car" },
    { spanish: "la casa", english: "house" },
    { spanish: "la ciudad", english: "city" },
    { spanish: "el pueblo", english: "town, people" },
    { spanish: "el campo", english: "countryside, field" },
    { spanish: "la calle", english: "street" },
    { spanish: "la escuela", english: "school" },
    { spanish: "el colegio", english: "school, college" },
    { spanish: "la universidad", english: "university" },
    { spanish: "el libro", english: "book" },
    { spanish: "la palabra", english: "word" },
    { spanish: "la pregunta", english: "question" },
    { spanish: "la respuesta", english: "answer" },
    { spanish: "el idioma", english: "language" },
    { spanish: "el español", english: "Spanish" },
    { spanish: "el inglés", english: "English" },
    { spanish: "el francés", english: "French" },
    { spanish: "el alemán", english: "German" },
    { spanish: "el italiano", english: "Italian" },
    { spanish: "el amigo", english: "friend (male)" },
    { spanish: "el perro", english: "dog" },
    { spanish: "el gato", english: "cat" },
    { spanish: "el animal", english: "animal" },
    { spanish: "el pez", english: "fish" },
    { spanish: "el pájaro", english: "bird" },
    { spanish: "el árbol", english: "tree" },
    { spanish: "la flor", english: "flower" },
    { spanish: "la planta", english: "plant" },
    { spanish: "el sol", english: "sun" },
    { spanish: "la luna", english: "moon" },
    { spanish: "la estrella", english: "star" },
    { spanish: "el mar", english: "sea" },
    { spanish: "el río", english: "river" },
    { spanish: "el lago", english: "lake" },
    { spanish: "la montaña", english: "mountain" },
    { spanish: "el bosque", english: "forest" },
    { spanish: "el cielo", english: "sky" },
    { spanish: "el aire", english: "air" },
    { spanish: "el agua", english: "water" },
    { spanish: "el fuego", english: "fire" },
    { spanish: "la tierra", english: "earth, land" },
    { spanish: "el viento", english: "wind" },
    { spanish: "la lluvia", english: "rain" },
    { spanish: "la nieve", english: "snow" },
    { spanish: "el calor", english: "heat" },
    { spanish: "el frío", english: "cold" },
    { spanish: "la comida", english: "food" },
    { spanish: "la bebida", english: "drink" },
    { spanish: "el pan", english: "bread" },
    { spanish: "el queso", english: "cheese" },
    { spanish: "la carne", english: "meat" },
    { spanish: "el pollo", english: "chicken" },
    { spanish: "el pescado", english: "fish (food)" },
    { spanish: "la fruta", english: "fruit" },
    { spanish: "la verdura", english: "vegetable" },
    { spanish: "la ensalada", english: "salad" },
    { spanish: "la sopa", english: "soup" },
    { spanish: "el huevo", english: "egg" },
    { spanish: "el arroz", english: "rice" },
    { spanish: "la leche", english: "milk" },
    { spanish: "el café", english: "coffee" },
    { spanish: "el té", english: "tea" },
    { spanish: "el vino", english: "wine" },
    { spanish: "la cerveza", english: "beer" },
    { spanish: "el azúcar", english: "sugar" },
    { spanish: "la sal", english: "salt" },
    { spanish: "la pimienta", english: "pepper" },
    { spanish: "el aceite", english: "oil" },
    { spanish: "la mantequilla", english: "butter" },
    { spanish: "el postre", english: "dessert" },
    { spanish: "el pastel", english: "cake" },
    { spanish: "el helado", english: "ice cream" },
    { spanish: "el chocolate", english: "chocolate" },
    { spanish: "el desayuno", english: "breakfast" },
    { spanish: "el almuerzo", english: "lunch" },
    { spanish: "la cena", english: "dinner" },
    { spanish: "el restaurante", english: "restaurant" },
    { spanish: "el bar", english: "bar" },
    { spanish: "la mesa", english: "table" },
    { spanish: "la silla", english: "chair" },
    { spanish: "el plato", english: "plate, dish" },
    { spanish: "el vaso", english: "glass" },
    { spanish: "la taza", english: "cup" },
    { spanish: "el cuchillo", english: "knife" },
    { spanish: "el tenedor", english: "fork" },
    { spanish: "la cuchara", english: "spoon" },
    { spanish: "la servilleta", english: "napkin" },
    { spanish: "la cuenta", english: "bill, check" },
    { spanish: "el dinero", english: "money" },
    { spanish: "el euro", english: "euro" },
    { spanish: "el dólar", english: "dollar" },
    { spanish: "el centavo", english: "cent" },
    { spanish: "el banco", english: "bank" },
    { spanish: "la tienda", english: "store, shop" },
    { spanish: "el supermercado", english: "supermarket" },
    { spanish: "el mercado", english: "market" },
    { spanish: "el precio", english: "price" },
    { spanish: "la oferta", english: "offer, sale" },
    { spanish: "el regalo", english: "gift" },
    { spanish: "la ropa", english: "clothes" },
    { spanish: "el zapato", english: "shoe" },
    { spanish: "la camisa", english: "shirt" },
    { spanish: "el pantalón", english: "pants" },
    { spanish: "la falda", english: "skirt" },
    { spanish: "el vestido", english: "dress" },
    { spanish: "el abrigo", english: "coat" },
    { spanish: "la chaqueta", english: "jacket" },
    { spanish: "el sombrero", english: "hat" },
    { spanish: "la corbata", english: "tie" },
    { spanish: "el reloj", english: "watch, clock" },
    { spanish: "la bolsa", english: "bag, purse" },
    { spanish: "el paraguas", english: "umbrella" },
    { spanish: "el teléfono", english: "telephone" },
    { spanish: "el móvil", english: "cell phone" },
    { spanish: "el ordenador", english: "computer" },
    { spanish: "la computadora", english: "computer" },
    { spanish: "el correo", english: "mail" },
    { spanish: "el mensaje", english: "message" },
    { spanish: "la carta", english: "letter" },
    { spanish: "el periódico", english: "newspaper" },
    { spanish: "la revista", english: "magazine" },
    { spanish: "la noticia", english: "news" },
    { spanish: "el programa", english: "program" },
    { spanish: "la película", english: "movie" },
    { spanish: "la música", english: "music" },
    { spanish: "la canción", english: "song" },
    { spanish: "el arte", english: "art" },
    { spanish: "el cuadro", english: "painting" },
    { spanish: "la foto", english: "photo" },
    { spanish: "el deporte", english: "sport" },
    { spanish: "el juego", english: "game" },
    { spanish: "el equipo", english: "team" },
    { spanish: "el partido", english: "match, game" },
    { spanish: "el gol", english: "goal" },
    { spanish: "el jugador", english: "player (male)" },
    { spanish: "la jugadora", english: "player (female)" },
    { spanish: "el ejercicio", english: "exercise" },
    { spanish: "la salud", english: "health" },
    { spanish: "el médico", english: "doctor (male)" },
    { spanish: "la médica", english: "doctor (female)" },
    { spanish: "el hospital", english: "hospital" },
    { spanish: "la farmacia", english: "pharmacy" },
    { spanish: "la medicina", english: "medicine" },
    { spanish: "el dolor", english: "pain" },
    { spanish: "la enfermedad", english: "illness" },
    { spanish: "la fiebre", english: "fever" },
    { spanish: "el accidente", english: "accident" },
    { spanish: "el seguro", english: "insurance" },
    { spanish: "el viaje", english: "trip, travel" },
    { spanish: "el avión", english: "airplane" },
    { spanish: "el tren", english: "train" },
    { spanish: "el autobús", english: "bus" },
    { spanish: "el metro", english: "subway" },
    { spanish: "el taxi", english: "taxi" },
    { spanish: "el billete", english: "ticket" },
    { spanish: "el pasaporte", english: "passport" },
    { spanish: "la maleta", english: "suitcase" },
    { spanish: "el hotel", english: "hotel" },
    { spanish: "la habitación", english: "room" },
    { spanish: "la llave", english: "key" },
    { spanish: "el mapa", english: "map" },
    { spanish: "la playa", english: "beach" },
    { spanish: "la piscina", english: "swimming pool" },
    { spanish: "el parque", english: "park" },
    { spanish: "el centro", english: "center, downtown" },
    { spanish: "la iglesia", english: "church" },
    { spanish: "el museo", english: "museum" },
    { spanish: "el cine", english: "cinema" },
    { spanish: "el teatro", english: "theater" },
    { spanish: "el banco", english: "bank" },
    { spanish: "el edificio", english: "building" },
    { spanish: "la oficina", english: "office" },
    { spanish: "el piso", english: "floor, apartment" },
    { spanish: "la puerta", english: "door" },
    { spanish: "la ventana", english: "window" },
    { spanish: "la pared", english: "wall" },
    { spanish: "el techo", english: "ceiling, roof" },
    { spanish: "el suelo", english: "floor, ground" },
    { spanish: "la luz", english: "light" },
    { spanish: "la sombra", english: "shadow, shade" },
    { spanish: "el color", english: "color" },
    { spanish: "el tamaño", english: "size" },
    { spanish: "la forma", english: "shape" },
    { spanish: "el número", english: "number" },
    { spanish: "el lado", english: "side" },
    { spanish: "el centro", english: "center" },
    { spanish: "el principio", english: "beginning" },
    { spanish: "el fin", english: "end" },
    { spanish: "la parte", english: "part" },
    { spanish: "el medio", english: "middle, means" },
    { spanish: "el tipo", english: "type, kind" },
    { spanish: "el ejemplo", english: "example" },
    { spanish: "el modo", english: "way, manner" },
    { spanish: "la manera", english: "way, manner" },
    { spanish: "el uso", english: "use" },
    { spanish: "el motivo", english: "reason, motive" },
    { spanish: "la causa", english: "cause" },
    { spanish: "el resultado", english: "result" },
    { spanish: "la oportunidad", english: "opportunity" },
    { spanish: "el interés", english: "interest" },
    { spanish: "el amor", english: "love" },
    { spanish: "el miedo", english: "fear" },
    { spanish: "la sorpresa", english: "surprise" },
    { spanish: "la suerte", english: "luck" },
    { spanish: "el sueño", english: "dream, sleep" },
    { spanish: "la realidad", english: "reality" },
    { spanish: "la verdad", english: "truth" },
    { spanish: "la mentira", english: "lie" },
    { spanish: "la razón", english: "reason" },
    { spanish: "el sentido", english: "sense, meaning" },
    { spanish: "la idea", english: "idea" },
    { spanish: "el recuerdo", english: "memory" },
    { spanish: "el pensamiento", english: "thought" },
    { spanish: "la imagen", english: "image" },
    { spanish: "el plan", english: "plan" },
    { spanish: "el proyecto", english: "project" },
    { spanish: "el objetivo", english: "objective, goal" },
    { spanish: "la meta", english: "goal, target" },
    { spanish: "el cambio", english: "change" },
    { spanish: "el desarrollo", english: "development" },
    { spanish: "el crecimiento", english: "growth" },
    { spanish: "el movimiento", english: "movement" },
    { spanish: "el proceso", english: "process" },
    { spanish: "el paso", english: "step" },
    { spanish: "el nivel", english: "level" },
    { spanish: "la cantidad", english: "quantity, amount" },
    { spanish: "el valor", english: "value" },
    { spanish: "el precio", english: "price" },
    { spanish: "el peso", english: "weight" },
    { spanish: "la medida", english: "measure" },
    { spanish: "el número", english: "number" },
    { spanish: "el porcentaje", english: "percentage" },
    { spanish: "el total", english: "total" },
    { spanish: "la mitad", english: "half" },
    { spanish: "el cuarto", english: "quarter, room" },
    { spanish: "el tercio", english: "third" },
    { spanish: "el resto", english: "rest, remainder" },
    { spanish: "el grupo", english: "group" },
    { spanish: "la pareja", english: "pair, couple" },
    { spanish: "el conjunto", english: "set, group" },
    { spanish: "la clase", english: "class" },
    { spanish: "el tipo", english: "type, kind" },
    { spanish: "el ejemplo", english: "example" },
    { spanish: "el caso", english: "case, occasion" },
    { spanish: "el hecho", english: "fact" },
    { spanish: "el problema", english: "problem" },
    { spanish: "la solución", english: "solution" },
    { spanish: "la pregunta", english: "question" },
    { spanish: "la respuesta", english: "answer" },
    { spanish: "el error", english: "error" },
    { spanish: "la dificultad", english: "difficulty" },
    { spanish: "la posibilidad", english: "possibility" },
    { spanish: "la probabilidad", english: "probability" },
    { spanish: "el riesgo", english: "risk" },
    { spanish: "la seguridad", english: "security, safety" },
    { spanish: "el peligro", english: "danger" },
    { spanish: "la fuerza", english: "strength, force" },
    { spanish: "el poder", english: "power" },
    { spanish: "la energía", english: "energy" },
    { spanish: "la luz", english: "light" },
    { spanish: "la oscuridad", english: "darkness" },
    { spanish: "el sonido", english: "sound" },
    { spanish: "el ruido", english: "noise" },
    { spanish: "el silencio", english: "silence" },
    { spanish: "el olor", english: "smell" },
    { spanish: "el sabor", english: "taste" },
    { spanish: "el color", english: "color" },
    { spanish: "la forma", english: "shape" },
    { spanish: "el tamaño", english: "size" },
    { spanish: "el material", english: "material" },
    { spanish: "la materia", english: "matter, subject" },
    { spanish: "el objeto", english: "object" },
    { spanish: "la cosa", english: "thing" },
    { spanish: "el elemento", english: "element" },
    { spanish: "la parte", english: "part" },
    { spanish: "el conjunto", english: "set, group" },
    { spanish: "el sistema", english: "system" },
    { spanish: "el aparato", english: "device, apparatus" },
    { spanish: "la máquina", english: "machine" },
    { spanish: "el motor", english: "engine, motor" },
    { spanish: "el vehículo", english: "vehicle" },
    { spanish: "el coche", english: "car" },
    { spanish: "el autobús", english: "bus" },
    { spanish: "el tren", english: "train" },
    { spanish: "el avión", english: "airplane" },
    { spanish: "el barco", english: "boat, ship" },
    { spanish: "la bicicleta", english: "bicycle" },
    { spanish: "la moto", english: "motorcycle" },
    { spanish: "el camino", english: "road, way" },
    { spanish: "la carretera", english: "highway" },
    { spanish: "la calle", english: "street" },
    { spanish: "la avenida", english: "avenue" },
    { spanish: "la plaza", english: "square, plaza" },
    { spanish: "el puente", english: "bridge" },
    { spanish: "el túnel", english: "tunnel" },
    { spanish: "el semáforo", english: "traffic light" },
    { spanish: "la señal", english: "sign, signal" },
    { spanish: "el cruce", english: "crossing, intersection" },
    { spanish: "la esquina", english: "corner" },
    { spanish: "el centro", english: "center, downtown" },
    { spanish: "el barrio", english: "neighborhood" },
    { spanish: "la zona", english: "zone, area" },
    { spanish: "el distrito", english: "district" },
    { spanish: "la región", english: "region" },
    { spanish: "el país", english: "country" },
    { spanish: "la nación", english: "nation" },
    { spanish: "el estado", english: "state" },
    { spanish: "la provincia", english: "province" },
    { spanish: "la ciudad", english: "city" },
    { spanish: "el pueblo", english: "town, people" },
    { spanish: "el campo", english: "countryside, field" },
    { spanish: "la isla", english: "island" },
    { spanish: "la costa", english: "coast" },
    { spanish: "la playa", english: "beach" },
    { spanish: "la montaña", english: "mountain" },
    { spanish: "el valle", english: "valley" },
    { spanish: "el río", english: "river" },
    { spanish: "el lago", english: "lake" },
    { spanish: "el mar", english: "sea" },
    { spanish: "el océano", english: "ocean" },
    { spanish: "el bosque", english: "forest" },
    { spanish: "la selva", english: "jungle" },
    { spanish: "el desierto", english: "desert" },
    { spanish: "la tierra", english: "earth, land" },
    { spanish: "la roca", english: "rock" },
    { spanish: "la arena", english: "sand" },
    { spanish: "el volcán", english: "volcano" },
    { spanish: "el clima", english: "climate" },
    { spanish: "el tiempo", english: "time, weather" },
    { spanish: "la temperatura", english: "temperature" },
    { spanish: "el grado", english: "degree" },
    { spanish: "el viento", english: "wind" },
    { spanish: "la lluvia", english: "rain" },
    { spanish: "la nieve", english: "snow" },
    { spanish: "el hielo", english: "ice" },
    { spanish: "la tormenta", english: "storm" },
    { spanish: "el trueno", english: "thunder" },
    { spanish: "el relámpago", english: "lightning" },
    { spanish: "la nube", english: "cloud" },
    { spanish: "el sol", english: "sun" },
    { spanish: "la luna", english: "moon" },
    { spanish: "la estrella", english: "star" }
];

export { spanishNouns };